"""
Django settings for LearningPlatform project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import logging
from logging.handlers import RotatingFileHandler
from django.core.management.utils import get_random_secret_key
import structlog # Added for structlog configuration

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("LEARN_OPS_DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False")
DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False")
ALLOWED_HOSTS = os.getenv(
    "LEARN_OPS_ALLOWED_HOSTS", "learning.nss.team,learningapi.nss.team,127.0.0.1,localhost").split(",")
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'corsheaders',
    'django_structlog', # Added for structlog integration
    'LearningAPI',
]

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = False

CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5002',
    'http://127.0.0.1:5002',
    'https://learning.nss.team',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_structlog.middlewares.RequestMiddleware', # Added for structlog request context
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Structlog Configuration
STRUCTLOG_DEFAULTS = {
    "cache_logger_on_first_use": True,
    "wrapper_class": "structlog.make_filtering_bound_logger",
    "processors": [
        # Add shared processors for all loggers
        "structlog.stdlib.add_logger_name",
        "structlog.stdlib.add_log_level",
        "structlog.processors.TimeStamper",
        "structlog.processors.StackInfoRenderer",
        "structlog.processors.format_exc_info",
        "structlog.processors.CallsiteParameterAdder", # Adds module, funcname, lineno
        "structlog.dev.ConsoleRenderer" if DEBUG else "structlog.processors.JSONRenderer",
    ],
    "logger_factory": "structlog.stdlib.LoggerFactory",
    "find_caller_level": 2,
}

# Configure CallsiteParameterAdder to include specific parameters
# This should be a tuple of strings, e.g., ("filename", "lineno", "func_name", "module")
# For example, to add module, funcname, and lineno:
STRUCTLOG_DEFAULTS["processors"].insert(
    STRUCTLOG_DEFAULTS["processors"].index("structlog.processors.CallsiteParameterAdder") + 1,
    structlog.processors.CallsiteParameterAdder(
        {
            structlog.processors.CallsiteParameter.FILENAME,
            structlog.processors.CallsiteParameter.LINENO,
            structlog.processors.CallsiteParameter.FUNC_NAME,
            structlog.processors.CallsiteParameter.MODULE,
        }
    )
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50
}

ROOT_URLCONF = 'LearningPlatform.urls'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LearningPlatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv("LEARN_OPS_DB"),
        'USER': os.getenv("LEARN_OPS_USER"),
        'PASSWORD': os.getenv("LEARN_OPS_PASSWORD"),
        'HOST': os.getenv("LEARN_OPS_HOST"),
        'PORT': os.getenv("LEARN_OPS_PORT"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Set to False to allow structlog to take over
    'formatters': {
        'json_formatter': {
            '()': 'structlog.stdlib.ProcessorFormatter',
            'processor': 'structlog.processors.JSONRenderer',
        },
        'console_formatter': {
            '()': 'structlog.stdlib.ProcessorFormatter',
            'processor': 'structlog.dev.ConsoleRenderer',
        },
        'standard': { # Keep existing standard formatter if needed for non-structlog logs
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'console_formatter' if DEBUG else 'json_formatter', # Use structlog formatters
        },
        'logfile': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
            'maxBytes': 50000,
            'backupCount': 2,
            'formatter': 'json_formatter', # Use structlog JSON formatter for file
        },
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'INFO', # Adjust level as needed
        },
        'django.request': {
            'handlers': ['console', 'logfile'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'logfile'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO', # Adjust level as needed
            'propagate': False,
        },
        'LearningPlatform': { # Your project's main logger
            'handlers': ['console', 'logfile'],
            'level': 'DEBUG',
            'propagate': False, # Prevent double logging if root logger also handles
        },
        'structlog': { # This logger captures structlog output
            'handlers': ['console', 'logfile'],
            'level': 'INFO', # Set a default level for structlog
            'propagate': False,
        },
        '': { # Root logger
            'handlers': ['console', 'logfile'],
            'level': 'INFO', # Default level for anything not explicitly configured
        }
    }
}

# Configure structlog to use the standard library logging
structlog.configure(
    processors=STRUCTLOG_DEFAULTS["processors"],
    logger_factory=STRUCTLOG_DEFAULTS["logger_factory"],
    wrapper_class=STRUCTLOG_DEFAULTS["wrapper_class"],
    cache_logger_on_first_use=STRUCTLOG_DEFAULTS["cache_logger_on_first_use"],
)

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "/var/www/learning.nss.team/static"
SITE_ID = 1
